spring:
  datasource:
    url : YOUR_URL
    username : yu_ai_agent
    password : YOUR_PW
  ai:
    dashscope:
      api-key: YOUR_API_KEY
      chat:
        model: qwen_plus

search-api:
  api-key : YOUR_API_KEY

